### ISSUE TITLE
Проблема с листингом юзеров

### ISSUE THREAD

**Issue by Tr0llt3ch** [Zazza/fm#1]
При создании нового юзера без привелегей администратора он не отображается в списке всех юзеров.

**Comment by Zazza** [comment]
Ошибку исправил. Это было связано с переносом почтовика из другого проекта.

**Comment by Tr0llt3ch** [comment]
Куда делать донат?

**Comment by Tr0llt3ch** [comment]
Странно у меня проблема осталась:
http://flic.kr/p/bkTwfA - интерфейс
http://flic.kr/p/byNoCc - база

**Comment by Zazza** [comment]
Если это ранее добавленные пользователи, то нужно заново их добавить. Изменилась функция добавляющая данные в таблицу users_priv. Старые данные так и остались. Лишних юзеров можно удалить из таблицы.
