### ISSUE TITLE
Не сохраняются Большие файлы

### ISSUE THREAD

**Issue by wbread** [Zazza/fm#12]
При загрузке больших файлов, примерно все что больше 10Мб, они после загрузки пропадают из списков.

**Comment by Zazza** [comment]
Это проблема apache, nginx, php, denwer или т.д.

**Comment by Zazza** [comment]
Increase upload filesize limits:
php.ini:

upload_max_filesize = [NUM]M
post_max_size = [NUM]M

nginx.conf:

client_max_body_size = [NUM]M

Для apache поможет гугл
