### ISSUE TITLE
Запрос функцианала

### ISSUE THREAD

**Issue by hoaryhedgehog** [Zazza/fm#2]
1. Возможность удалять файлы.
2. Удалять файлы и папки может только их создатель либо админ. Точнее как это сделано у вас помечать их как закрытые.

Жаль у вас нет PayPal, донат будет сделать мне трудновато.

**Comment by Zazza** [comment]
Файлы по настоящему (совсем) удалить нельзя, можно только пометить их в БД как удалённые. Система создавалась с расчётом на пользователей, которые уже смогли потерять важные файлы.
Удалять, да, может только их создатель, либо админ.
Из-за того что файлы физически не удаляются - требования к свободному месту на жёстком диске соответствующие. У меня уже была идея сделать возможность удаления для админа FM, но это немного противоречит самой концепции не терять файлы и всегда хранить полное "дерево" изменений.

Про донат я как-то раньше не думал. Т.к. я использую кое где robokass-у, сделал http://otms-project.ru/donate/ через неё.

**Comment by hoaryhedgehog** [comment]
Попытаюсь реализовать первую возможность в качесве плагина.
А вот по второй не вижу в интерфейсе пункта удалить под файлом. Только под папкой. Хотя код для пометки файла как удаленного присутсвует.

**Comment by Zazza** [comment]
там, немножко, с первого взгляда не логично сделано: нужно выделить файлы для удаления (нажав на области файла ниже иконки, например не название файла) и нажать кнопку удалить - вверху на панели.

**Comment by hoaryhedgehog** [comment]
My bad.
Не заметил. А вот проверки на того кто создал данный файл или папку для удаления нету.
Это было бы плюсом для меня =)
Изначально это задумывалось? И каждый может удалять все?

**Comment by Zazza** [comment]
получается так, удалить файл может любой у кого есть доступ к файлу. Здесь права доступа железные - доступ есть и доступа нету. Просто первоначально FM создавался для работы людьми, для которых слова "права доступа" - ругательство.
Вобщем, мне кажется, логично сделать разделение прав на чтение, на запись и на просмотр существаования файла (не исполнение как в unix) ИЛИ оставить как есть, но сделать логирование действий, чтобы администратор FM смог бы видеть все действия и если кто-то файл потрёт - наказать и файл восстановить.

**Comment by hoaryhedgehog** [comment]
Да с сидемой подобной Unix провам доступа было бы очень хорошо.
Проэкт я форкнул попытаюсь что то подобное реализовать. В моих реалиях оно нужно.
