### ISSUE TITLE
Не найдены  папки ajax/users/ и ajax/users/

### ISSUE THREAD

**Issue by gvkapral** [Zazza/fm#3]
Не подскажете в чем может быть причина? В firebug пишет,  что не найдены данные папки  ajax/users/ и ajax/users/ после входа с ученой записью filemanager.

**Comment by Zazza** [comment]
не могу уловить проблему. А может скриншот прикрепить или на почту мне отправить?

**Comment by gvkapral** [comment]
Извиняюсь, может не корректно составил вопрос. 
<a href='http://www.pictureshack.ru/view_9531fm.jpg'><img src='http://www.pictureshack.ru/thumbs/9531fm.jpg' border='0'</a>

**Comment by Zazza** [comment]
Так понятнее /fm/ajax/fm/ - и не должен быть найден. Его нет. Тут срабатывает роутинг, чтобы преобразовать путь в понтяный системе. Роутинг это специальный класс (файл) в системе + правила в файле .htaccess в корне системы.
Вывод: или у вас почему-то отсутсвует файл /fm/.htaccess или rewite нужно включить командой: "sudo a2enmod rewite && sudo service apache2 restart" в ubuntu

**Comment by gvkapral** [comment]
Спасибо! Недавно ставил систему заново, забыл включить =)
