### ISSUE TITLE
could not find driver

### ISSUE THREAD

**Issue by Keroronsk** [Zazza/fm#8]
Здравствуйте. Подскажите, в чём может быть проблема. Поставил Апач, PHP и MySQL, открываю index.php, и вижу такую ошибку:
Fatal error: Call to a member function setAttribute() on a non-object in C:\Program Files\Apache Software Foundation\Apache2.2\htdocs\system\library\Engine\Bootstrap.php on line 89

phpinfo() и mysql_connect('localhost', 'fmuser', 'fmpassword'); работают нормально.

**Comment by Zazza** [comment]
Здравствуйте, у вас не установлено расширение для доступа к базе данных - PDO. mysql_connect - это другое.

http://php.net/manual/en/pdo.installation.php

**Comment by Keroronsk** [comment]
Да, действительно, спасибо. И ещё понадобилось включить mbstring (в мануале на сайте про это не упомянуто), и всё заработало.
