### ISSUE TITLE
Изображение без иконки

### ISSUE THREAD

**Issue by KKKozlowski** [Zazza/fm#9]
Если не установлен php-gd, или если при генерации иконки изображения php упирается в память, то файл остается без иконки.

Для красоты я сделал следущее:
system/Model/File.php:
было:

``` code
                           if ($ico == "preview") {
                                        $ico = $this->registry['path']['upload'] . "_thumb/" . $md5;
                                } else {
                                        $ico = "img/ftypes/" . $ico;
                                }
```

стало:

``` code
                           if ($ico == "preview") {
                                        $ico = $this->registry['path']['upload'] . "_thumb/" . $md5;
                                        if (!is_readable($ico)) $ico = "img/ftypes/image.png";
                                } else {
                                        $ico = "img/ftypes/" . $ico;
                                }
```

PS может в конфиге добавить опцию: "делать иконки для изображений", чтобы была возможность не "мучать" хостинг без GD, и с малым количеством выделенной памяти под php
system/config.ini:

``` code
[fm]
* * *
genImageThumb = false
```

system/Model/Save.php:

``` code
            if  ( ($this->registry["fm"]["genImageThumb"] == true) and ( (strtolower($ext) == "gif") or (strtolower($ext) == "png") or (strtolower($ext) == "jpg") or (strtolower($ext) == "jpeg") ) ) {
                $thumb = new Model_Thumb();
                $thumb->img_resize($uploadDirectory . $this->md5, $_thumbPath . $this->md5, 150, 120);
            };
```

**Comment by Zazza** [comment]
Спасибо поправил! Единственное, сделал так:

if ($ico == "preview") {
     $ico = $this->registry['path']['upload'] . "_thumb/" . $md5;
     if (!is_readable($this->registry['path']['root'] . "/" . $ico)) { $ico = "img/ftypes/image.png"; }
} else {
     $ico = "img/ftypes/" . $ico;
}

указав абсолютный путь до previw
